<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Customer\Block\Account\AuthorizationLink */
$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>
<li class="nav item"><a href="<?php echo $this->getBaseUrl() ?>checkout/"><?php echo __('Checkout') ?></a></li>
<li class="authorization-link" data-label="<?php echo $block->escapeHtml(__('or')); ?>">
    <a class="link-authorization" <?php /* @escapeNotVerified */ echo $block->getLinkAttributes(); ?><?php /* @escapeNotVerified */ echo $dataPostParam; ?>>
        <?php echo $block->escapeHtml($block->getLabel()); ?>

    </a> 
</li>

