<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block newsletter" data-role="collapsible">
	<div class="title-left">
		<div class="title group-title1" data-role="title"><h2>Sign up for newsletter</h2></div>
		
	</div>


	<div class="content-newsletter" data-role="content">
		<form class="form subscribe"
			novalidate
			action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
			method="post"
			data-mage-init='{"validation": {"errorClass": "mage-error"}}'
			id="newsletter-validate-detail">
			<div class="field_newsletter">
				<label class="label" for="newsletter"><span><?php /* @escapeNotVerified */ echo __('Sign Up for Our Newsletter:') ?></span></label>
				<div class="control">
					<input name="email" type="email" id="newsletter"
								placeholder="<?php /* @escapeNotVerified */ echo __('Email Address') ?>"
								data-validate="{required:true, 'validate-email':true}"/>
					<div class="actions">
						<button class="action subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
							<span><?php /* @escapeNotVerified */ echo __('Send') ?></span>
						</button>
					</div>
				</div>
			</div>

		</form>
	</div>
	
</div>
